# Generated by Django 6.0 on 2026-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
