# Generated by Django 6.0 on 2026-01-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_address_application_experience_and_more'),
        ('jobs', '0002_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
    ]
