# Generated by Django 6.0 on 2026-01-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_seen_alter_application_job'),
        ('jobs', '0002_job_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_seen',
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
