# Generated by Django 6.0 on 2026-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_is_seen_alter_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
