# Generated by Django 6.0 on 2026-01-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_is_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_seen',
            new_name='is_seen_by_employer',
        ),
    ]
