# Generated by Django 6.0 on 2026-01-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_rename_is_seen_application_is_seen_by_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_seen_by_employer',
        ),
    ]
