# Generated by Django 6.0 on 2026-01-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_notification_job_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
