# Generated by Django 6.0 on 2026-01-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_notification_job_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
