# Generated by Django 5.2.4 on 2026-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_notification_job_notification_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job_seeker',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
